### ISSUE TITLE
Either upper or lowercase

### ISSUE THREAD

**Issue by sen1** [raymondhuggins/intro-data-capstone-musclehub#1]
https://github.com/raymondhuggins/intro-data-capstone-musclehub/blob/49f96dcc0b6d24ce3436320ca54bf7053a67b4de/Capstone_Project/musclehub.py#L112-L140

Great work. The sql statements like `AND`, `ON`, `LEFT` are not case sensitive. Some people use upper case some lower. However, the mix is very uncommon. I would suggest using either upper case or lower -- whatever you prefer.

**Comment by raymondhuggins** [comment]
I didn`t mean for that to be lowercase that was supposed to be upper.
