### ISSUE TITLE
Assign to variables

### ISSUE THREAD

**Issue by sen1** [raymondhuggins/intro-data-capstone-musclehub#2]
https://github.com/raymondhuggins/intro-data-capstone-musclehub/blob/49f96dcc0b6d24ce3436320ca54bf7053a67b4de/Capstone_Project/musclehub.py#L257

Assign it to variables. For someone does not know the output format cant make out of the 4 outputs. All of the outputs are important but the only thing we look here is the p-value which is the second item. To ignore few variables, you use `_` character:
```
_, pval, _, _ = chi2_contingency(x) 
```

**Comment by raymondhuggins** [comment]
Thank you for showing me that I wasn`t sure how to notate that.
