### ISSUE TITLE
Summary

### ISSUE THREAD

**Issue by sen1** [raymondhuggins/intro-data-capstone-musclehub#4]
Great work! I probably won’t have much to say here because you pretty much nailed it all the way through.

Your Python work was excellent and very readable. There are a couple points where your code could be accomplished a bit more efficiently, but everything worked the way it was supposed to.

Presentation: I think your graphs look excellent.

You seem to be missing the whole point of this project. We dont want "Qualitative" statements which may or may not be true. The purpose of this exercise is to look into the data and make some quantitative statements. These statements are based on fact (data) and scientific. You will need to look into the p-values and see if it is significant. If it is then which direction. It will prove if Janet is wrong or right. The conclusion is scientific and not a qualitative statement.

Good job overall.

**Comment by raymondhuggins** [comment]
Thank you for your input, I wasn`t  sure how to explain it, or how to word it, it was difficult for me to understand I knew what to do, but had difficulty.
